### PR TITLE
Fix backend server installation

### LINKED ISSUE #4: Running `npm install` for server fails
# Context
Running `npm install` for the server component of the project fails due to an issue with the [bcrypt module](https://www.npmjs.com/package/bcrypt) (used for password hashing). This may be some sort of versioning issue, see [here for reference](https://stackoverflow.com/questions/29320201/error-installing-bcrypt-with-npm).
```
...
npm WARN old lockfile 
npm WARN deprecated bcrypt@3.0.1: versions < v5.0.0 do not handle NUL in passwords properly
npm ERR! code 1
npm ERR! path /Users/koger/git-projects/macro-tracker/server/node_modules/bcrypt
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
npm ERR!   CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
npm ERR!   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
npm ERR!   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
npm ERR!   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
...
```

# AC
* Fix the dependency issue so that the server can install and run properly

### PR DESCRIPTION
**Pull request by mkogerd**
Resolves #4 
# Background/Context
Trying to install the backend server with `npm install` would fail due to an outdated `bcrypt` dependency (see #4 for more details). Updating this dependency to the latest version solved the problem.

Additionally, while testing further I discovered that connecting to recent versions of MySQL with the `mysql` client doesn't work out of the box and will result in a `ER_NOT_SUPPORTED_AUTH_MODE`. Changing over to the more recently maintained `mysql2` client fixes this problem without having to manually edit user data in the database. 

# What was changed
* Updated `bycrypt` from `3.0.1` to `5.1.0`
* Replaced `mysql` client with `mysql2` client

### CODE REVIEW

File: server/api.js [hunk 1]
```diff
@@ -41,8 +41,11 @@ const con = mysql.createConnection({
 });
 
 con.connect(function(err) {
-	if (err) throw err;
-	console.log("Connected!");
+	if (err) {
```
Comment (mkogerd) [inline server/api.js:44]: This change is just making error logging a bit clearer and is unrelated to the dependency change.
